spring.application.name=shopsmart
server.port=8080
spring.datasource.url=jdbc:h2:mem:shopsmartdb
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true